apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-template-dev
  namespace: distrischool
  labels:
    app: microservice-template-dev
    version: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-template-dev
  template:
    metadata:
      labels:
        app: microservice-template-dev
        version: dev
    spec:
      containers:
      - name: microservice-template-dev
        image: microservice-template-dev:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: microservice-template-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
