apiVersion: v1
kind: Service
metadata:
  name: microservice-template-dev-service
  namespace: distrischool
  labels:
    app: microservice-template-dev
spec:
  type: ClusterIP
  selector:
    app: microservice-template-dev
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-template-dev-nodeport
  namespace: distrischool
  labels:
    app: microservice-template-dev
spec:
  type: NodePort
  selector:
    app: microservice-template-dev
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http

